# Generated by Django 3.1.2 on 2022-05-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_user_id', models.IntegerField(default=-1)),
                ('block_blocker_id', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_sender_id', models.IntegerField(default=-1)),
                ('chat_sender_username', models.CharField(default='', max_length=64)),
                ('chat_receiver_id', models.IntegerField(default=-1)),
                ('chat_receiver_username', models.CharField(default='', max_length=64)),
                ('chat_content', models.CharField(default='', max_length=10240)),
                ('chat_time', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_user_id', models.IntegerField(default=-1)),
                ('comment_post_id', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_user_id', models.IntegerField(default=-1)),
                ('doc_name', models.CharField(blank=True, default='', max_length=128)),
                ('doc_path', models.CharField(default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Doc',
                'verbose_name_plural': 'Docs',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_user_id', models.IntegerField(default=-1)),
                ('like_post_id', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_user_id', models.IntegerField(default=-1)),
                ('post_file_id', models.IntegerField(default=-1)),
                ('post_title', models.CharField(blank=True, default='', max_length=128)),
                ('post_text', models.CharField(blank=True, default='', max_length=10240)),
                ('post_type', models.IntegerField(default=-1)),
                ('post_location', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('subscribe_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscribe_user_id', models.IntegerField(default=-1)),
                ('subscribe_subscriber_id', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(default='', max_length=64)),
                ('user_password', models.CharField(default='', max_length=64)),
                ('user_mail', models.CharField(default='', max_length=256)),
                ('user_intro', models.CharField(default='', max_length=10240)),
                ('user_avatarid', models.IntegerField(default=-1)),
                ('user_loginJwt', models.CharField(default='', max_length=1024)),
                ('user_verification', models.BooleanField(default=False)),
                ('user_mailVerification', models.CharField(default='', max_length=1024)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
