# Generated by Django 3.1.2 on 2022-05-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_receiver_username',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_sender_username',
        ),
    ]
