# Generated by Django 3.1.2 on 2022-05-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220502_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='doc_name',
        ),
    ]
