# Generated by Django 3.1.2 on 2022-05-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_doc_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
