# Generated by Django 3.1.2 on 2022-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_post_cnt_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
