# Generated by Django 3.1.2 on 2022-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(blank=True, default='', max_length=10240),
        ),
    ]
