# Generated by Django 3.1.2 on 2022-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
